export const ERROR_CATEGORIES = [
    "DATABASE_FAILURE",
    "PAYMENT_FAILURE",
    "AUTHENTICATION_FAILURE",
    "NETWORK_TIMEOUT",
    "RATE_LIMITING",
    "SERVICE_UNAVAILABLE",
    "CONFIGURATION_ERROR",
    "DEPENDENCY_FAILURE",
    "SECURITY_VIOLATION",
    "UNKNOWN_SYSTEM_ERROR"
];
